version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambientese
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: grupo5
      JWT_SECRET: GCJrc9*tnU(Y73E@SD&VIHqN  # Defina isso conforme necessário
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ambientese?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EMAIL: your_email@example.com  # Defina isso conforme necessário
      EMAIL_HOST: smtp.example.com  # Defina isso conforme necessário
      EMAIL_PORT: 587  # Defina isso conforme necessário
      EMAIL_APP_PASSWORD: your_email_app_password  # Defina isso conforme necessário
    depends_on:
      - db

  jaeger-api:
    image: jaegertracing/all-in-one:latest
    platform: linux/arm64
    container_name: jaeger-api
    ports:
      - 16686:16686
    depends_on:
      - collector-api

  collector-api:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector-api
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - 4317:4317
      - 4318:4318
      - 8889:8889
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
    restart: always
    ports:
      - '9090:9090'
    depends_on:
      - collector-api

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # Sonar Scanner for code analysis
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_LOGIN: sqa_a68c85923e7a13b25b13348d90d5ba19df741e11
    volumes:
      - "/c/Users/lgabr/OneDrive - Biopark Educação/Área de Trabalho/Ambientese/projeto-integrador-ambientese:/usr/src"  # Caminho corrigido para Windows

    entrypoint:
      - sonar-scanner
      - -Dsonar.projectKey=projeto-integrador-ambientese
      - -Dsonar.sources=/usr/src
      - -Dsonar.host.url=http://sonarqube:9000
      - -Dsonar.login=sqa_a68c85923e7a13b25b13348d90d5ba19df741e11

  # PostgreSQL for SonarQube
  sonarqube-db:
    image: postgres:13-alpine
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube-postgresql-data:/var/lib/postgresql/data

  # SonarQube service
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    ports:
      - "9000:9000"  # SonarQube UI is accessible on port 9000
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions

volumes:
  mysql-data:
  sonarqube-postgresql-data:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions: